---
dependencies: []

galaxy_info:
  author: josmase
  description: Install and configure a network-accessible Ollama server on Arch Linux
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ollama
    - llm
    - ai
    - server
    - archlinux
    - ubuntu
