---
dependencies:
  - role: container/docker_setup

galaxy_info:
  author: josmase
  description: Manages Docker container deployments using templates
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - containers
    - compose
    - templates
    - deployment