---
dependencies:
  - role: container/docker_setup

galaxy_info:
  author: josmase
  description: Installs and configures Obico server for 3D printer monitoring
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - obico
    - 3dprinting
    - monitoring
    - docker
