---
dependencies:
  - role: container/docker_setup

galaxy_info:
  author: josmase
  description: Run Wyoming Whisper (STT) and Piper (TTS) containers for Home Assistant
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - wyoming
    - whisper
    - piper
    - stt
    - tts
    - docker
